# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4900d21c644a2b7295b20c83550eee9a4317a7c44cadcffef5036e442fff037e588591f9c91301c53b25e8fb393c41822f694141cd78ff27e95f4581e4ba4888

test:
  secret_key_base: f1d2c39662008572718440c61da71d07f338c756bb67ca58fe8a2fe98a45fda7e287048e2af5b3299a31cc7a868729774830860506987e173caef7c4109d0524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
